---
- name: Install Apache Tomcat10 using ansible
  hosts: webservers
  become_method: sudo
  remote_user: azureuser
  vars:
  - artifact : $(artifacts)
  vars_files:
    - pass.yml
  become: true
  tasks:
    - name: Update the System Packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Create a Tomcat User
      user:
        name: tomcat

    - name: Create a Tomcat Group
      group:
        name: tomcat

#    - name: Install JAVA
#      apt:
#        name: default-jdk
#        state: present
#
    - name: Download Open JDK
      become: yes
      apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present

    - name: Create a Tomcat Directory
      file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        mode: 0755
        state: directory
       #recurse: yes

    - name: download & unarchive tomcat10
      unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.tar.gz
        dest: /opt/tomcat
        remote_src: yes
       #extra_opts: [--strip-components=1]

    - name: Change ownership of tomcat directory
      file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
       #state: directory

    - name: Creating service for Apache tomcat.
      file:
        path: /etc/systemd/system/tomcat.service
        mode: u+rwx,g-rwx,o-x

    - name: Creating a service file
      become: yes
      copy: 
       content: |-
         [Unit]
         Description=Tomcat Service
         Requires=network.target
         After=network.target
         [Service]
         Type=forking
         User=tomcat
         Environment="CATALINA_PID=/opt/tomcat/logs/tomcat.pid"
         Environment="CATALINA_BASE=/opt/tomcat"
         Environment="CATALINA_HOME=/opt/tomcat"
         Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
         ExecStart=/opt/tomcat/bin/startup.sh
         ExecStop=/opt/tomcat8/bin/shutdown.sh
         Restart=on-abnormal
         [Install]
         WantedBy=multi-user.target
       dest: /etc/systemd/system/tomcat.service
       state: present

    - name: Reload the SystemD to re-read configurations
      become: yes
      systemd:
         daemon-reload: yes
    - name: Enable the tomcat service and start
      become: yes
      systemd:
         name: tomcat
         enabled: yes
         state: started 
    
    - name: Download war file
      become: yes
      shell: curl -u "{{ user }}":"{{ pass }}" -XGET 'https://demo2402.jfrog.io/artifactory/demo-artifact/{{ artifact }}.war' --output '/opt/tomcat/webapps/{{ artifact }}.war'

    - name: Change permission for war file
      file:
        path: /opt/tomcat/webapps/{{ artifact }}.war
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rwx,o=rwx"
        state: file
          
    - name: Stopping Tomcat Service
      shell: /opt/tomcat/bin/shutdown.sh

    - name: Starting Tomcat Service
      shell: nohup /opt/tomcat/bin/startup.sh
